/**
 * PaymentDetailsPage - Cell data from Google Sheets scheme
 * Generated from tmp/payment-details-sheet.json
 * Sheet: gid=403093960 (Classic Single-Item Invoice (Instruction))
 * Rows: 161-201
 * Generated: 2026-01-03T07:14:19.190Z
 */

import type { SchemeRowData, SchemeMerge } from '../../grid';

export const ROW_HEIGHTS = [
  21, // Row 1 (Sheet 161)
  21, // Row 2 (Sheet 162)
  21, // Row 3 (Sheet 163)
  21, // Row 4 (Sheet 164)
  21, // Row 5 (Sheet 165)
  21, // Row 6 (Sheet 166)
  21, // Row 7 (Sheet 167)
  21, // Row 8 (Sheet 168)
  21, // Row 9 (Sheet 169)
  21, // Row 10 (Sheet 170)
  21, // Row 11 (Sheet 171)
  21, // Row 12 (Sheet 172)
  29, // Row 13 (Sheet 173)
  29, // Row 14 (Sheet 174)
  29, // Row 15 (Sheet 175)
  29, // Row 16 (Sheet 176)
  21, // Row 17 (Sheet 177)
  21, // Row 18 (Sheet 178)
  21, // Row 19 (Sheet 179)
  21, // Row 20 (Sheet 180)
  21, // Row 21 (Sheet 181)
  21, // Row 22 (Sheet 182)
  21, // Row 23 (Sheet 183)
  21, // Row 24 (Sheet 184)
  21, // Row 25 (Sheet 185)
  77, // Row 26 (Sheet 186)
  21, // Row 27 (Sheet 187)
  21, // Row 28 (Sheet 188)
  21, // Row 29 (Sheet 189)
  21, // Row 30 (Sheet 190)
  26, // Row 31 (Sheet 191)
  21, // Row 32 (Sheet 192)
  21, // Row 33 (Sheet 193)
  21, // Row 34 (Sheet 194)
  21, // Row 35 (Sheet 195)
  161, // Row 36 (Sheet 196)
  21, // Row 37 (Sheet 197)
  115, // Row 38 (Sheet 198)
  21, // Row 39 (Sheet 199)
  24, // Row 40 (Sheet 200)
  57, // Row 41 (Sheet 201)
];

export const TOTAL_HEIGHT = 1227; // 41 rows

export const MERGES: SchemeMerge[] = [
  { startRow: 161, endRow: 164, startCol: 'A', endCol: 'I', rowSpan: 3, colSpan: 8 },
  { startRow: 161, endRow: 164, startCol: 'L', endCol: 'N', rowSpan: 3, colSpan: 2 },
  { startRow: 165, endRow: 166, startCol: 'J', endCol: 'N', rowSpan: 1, colSpan: 4 },
  { startRow: 169, endRow: 170, startCol: 'A', endCol: 'N', rowSpan: 1, colSpan: 13 },
  { startRow: 173, endRow: 173, startCol: 'A', endCol: 'C', rowSpan: 0, colSpan: 2 },
  { startRow: 173, endRow: 173, startCol: 'D', endCol: 'F', rowSpan: 0, colSpan: 2 },
  { startRow: 173, endRow: 173, startCol: 'H', endCol: 'I', rowSpan: 0, colSpan: 1 },
  { startRow: 174, endRow: 174, startCol: 'A', endCol: 'C', rowSpan: 0, colSpan: 2 },
  { startRow: 174, endRow: 174, startCol: 'D', endCol: 'H', rowSpan: 0, colSpan: 4 },
  { startRow: 175, endRow: 175, startCol: 'A', endCol: 'C', rowSpan: 0, colSpan: 2 },
  { startRow: 175, endRow: 175, startCol: 'H', endCol: 'M', rowSpan: 0, colSpan: 5 },
  { startRow: 176, endRow: 176, startCol: 'A', endCol: 'C', rowSpan: 0, colSpan: 2 },
  { startRow: 178, endRow: 179, startCol: 'A', endCol: 'C', rowSpan: 1, colSpan: 2 },
  { startRow: 178, endRow: 179, startCol: 'D', endCol: 'G', rowSpan: 1, colSpan: 3 },
  { startRow: 178, endRow: 179, startCol: 'H', endCol: 'M', rowSpan: 1, colSpan: 5 },
  { startRow: 180, endRow: 181, startCol: 'A', endCol: 'C', rowSpan: 1, colSpan: 2 },
  { startRow: 180, endRow: 181, startCol: 'D', endCol: 'F', rowSpan: 1, colSpan: 2 },
  { startRow: 180, endRow: 181, startCol: 'G', endCol: 'G', rowSpan: 1, colSpan: 0 },
  { startRow: 180, endRow: 180, startCol: 'H', endCol: 'J', rowSpan: 0, colSpan: 2 },
  { startRow: 185, endRow: 185, startCol: 'A', endCol: 'C', rowSpan: 0, colSpan: 2 },
  { startRow: 185, endRow: 187, startCol: 'D', endCol: 'E', rowSpan: 2, colSpan: 1 },
  { startRow: 186, endRow: 186, startCol: 'F', endCol: 'N', rowSpan: 0, colSpan: 8 },
  { startRow: 191, endRow: 191, startCol: 'A', endCol: 'N', rowSpan: 0, colSpan: 13 },
  { startRow: 195, endRow: 195, startCol: 'A', endCol: 'N', rowSpan: 0, colSpan: 13 },
  { startRow: 196, endRow: 196, startCol: 'A', endCol: 'N', rowSpan: 0, colSpan: 13 },
  { startRow: 197, endRow: 197, startCol: 'A', endCol: 'N', rowSpan: 0, colSpan: 13 },
  { startRow: 198, endRow: 198, startCol: 'A', endCol: 'N', rowSpan: 0, colSpan: 13 },
  { startRow: 200, endRow: 200, startCol: 'A', endCol: 'D', rowSpan: 0, colSpan: 3 },
  { startRow: 201, endRow: 201, startCol: 'A', endCol: 'D', rowSpan: 0, colSpan: 3 },
  { startRow: 201, endRow: 201, startCol: 'K', endCol: 'N', rowSpan: 0, colSpan: 3 },
];

export const ROWS: SchemeRowData[] = [
  // Row 1 (Sheet 161): 21px
  {
    row: 161,
    height: 21,
    cells: [
      { col: 'A', colNum: 1, value: "P a y m e n t   D e t a i l s", fontFamily: 'Cormorant Infant', fontSize: 30, bold: true, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'BOTTOM', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'B', colNum: 2 },
      { col: 'C', colNum: 3 },
      { col: 'D', colNum: 4 },
      { col: 'E', colNum: 5 },
      { col: 'F', colNum: 6 },
      { col: 'G', colNum: 7 },
      { col: 'H', colNum: 8 },
      { col: 'I', colNum: 9 },
      { col: 'J', colNum: 10, fontFamily: 'arial,sans,sans-serif', fontSize: 10, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'K', colNum: 11, fontFamily: 'arial,sans,sans-serif', fontSize: 10, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'L', colNum: 12, value: "E.", fontFamily: 'Rampart One', fontSize: 60, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'RIGHT', vAlign: 'MIDDLE', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'M', colNum: 13 },
      { col: 'N', colNum: 14 },
    ],
  },
  // Row 2 (Sheet 162): 21px
  {
    row: 162,
    height: 21,
    cells: [
      { col: 'A', colNum: 1 },
      { col: 'B', colNum: 2 },
      { col: 'C', colNum: 3 },
      { col: 'D', colNum: 4 },
      { col: 'E', colNum: 5 },
      { col: 'F', colNum: 6 },
      { col: 'G', colNum: 7 },
      { col: 'H', colNum: 8 },
      { col: 'I', colNum: 9 },
      { col: 'J', colNum: 10 },
      { col: 'K', colNum: 11 },
      { col: 'L', colNum: 12 },
      { col: 'M', colNum: 13 },
      { col: 'N', colNum: 14 },
    ],
  },
  // Row 3 (Sheet 163): 21px
  {
    row: 163,
    height: 21,
    cells: [
      { col: 'A', colNum: 1 },
      { col: 'B', colNum: 2 },
      { col: 'C', colNum: 3 },
      { col: 'D', colNum: 4 },
      { col: 'E', colNum: 5 },
      { col: 'F', colNum: 6 },
      { col: 'G', colNum: 7 },
      { col: 'H', colNum: 8 },
      { col: 'I', colNum: 9 },
      { col: 'J', colNum: 10 },
      { col: 'K', colNum: 11 },
      { col: 'L', colNum: 12 },
      { col: 'M', colNum: 13 },
      { col: 'N', colNum: 14 },
    ],
  },
  // Row 4 (Sheet 164): 21px
  {
    row: 164,
    height: 21,
    cells: [
      { col: 'A', colNum: 1 },
      { col: 'B', colNum: 2 },
      { col: 'C', colNum: 3 },
      { col: 'D', colNum: 4 },
      { col: 'E', colNum: 5 },
      { col: 'F', colNum: 6 },
      { col: 'G', colNum: 7 },
      { col: 'H', colNum: 8 },
      { col: 'I', colNum: 9 },
      { col: 'J', colNum: 10 },
      { col: 'K', colNum: 11 },
      { col: 'L', colNum: 12 },
      { col: 'M', colNum: 13 },
      { col: 'N', colNum: 14 },
    ],
  },
  // Row 5 (Sheet 165): 21px
  {
    row: 165,
    height: 21,
    cells: [
      { col: 'A', colNum: 1, fontFamily: 'Cormorant Infant', fontSize: 8, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL', borders: {"bottom":{"style":"DOTTED","width":1,"color":"rgb(204, 204, 204)"}} },
      { col: 'B', colNum: 2, fontFamily: 'Cormorant Infant', fontSize: 8, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL', borders: {"bottom":{"style":"DOTTED","width":1,"color":"rgb(204, 204, 204)"}} },
      { col: 'C', colNum: 3, fontFamily: 'Cormorant Infant', fontSize: 8, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL', borders: {"bottom":{"style":"DOTTED","width":1,"color":"rgb(204, 204, 204)"}} },
      { col: 'D', colNum: 4, fontFamily: 'Cormorant Infant', fontSize: 8, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL', borders: {"bottom":{"style":"DOTTED","width":1,"color":"rgb(204, 204, 204)"}} },
      { col: 'E', colNum: 5, fontFamily: 'Cormorant Infant', fontSize: 8, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL', borders: {"bottom":{"style":"DOTTED","width":1,"color":"rgb(204, 204, 204)"}} },
      { col: 'F', colNum: 6, fontFamily: 'Cormorant Infant', fontSize: 8, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL', borders: {"bottom":{"style":"DOTTED","width":1,"color":"rgb(204, 204, 204)"}} },
      { col: 'G', colNum: 7, fontFamily: 'Roboto Mono', fontSize: 8, italic: true, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL', borders: {"bottom":{"style":"DOTTED","width":1,"color":"rgb(204, 204, 204)"}} },
      { col: 'H', colNum: 8, fontFamily: 'Roboto Mono', fontSize: 8, italic: true, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL', borders: {"bottom":{"style":"DOTTED","width":1,"color":"rgb(204, 204, 204)"}} },
      { col: 'I', colNum: 9, fontFamily: 'Roboto Mono', fontSize: 10, bold: true, italic: true, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL', borders: {"bottom":{"style":"DOTTED","width":1,"color":"rgb(204, 204, 204)"}} },
      { col: 'J', colNum: 10, value: "<SubsidiaryEnglishName> *Spacified* \n<SubsidiaryChineseName> *Spacified*", fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'RIGHT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL', textRuns: [{"startIndex":0,"format":{}},{"startIndex":39,"format":{"fontFamily":"Iansui"}}] },
      { col: 'K', colNum: 11 },
      { col: 'L', colNum: 12 },
      { col: 'M', colNum: 13 },
      { col: 'N', colNum: 14 },
    ],
  },
  // Row 6 (Sheet 166): 21px
  {
    row: 166,
    height: 21,
    cells: [
      { col: 'A', colNum: 1, fontFamily: 'Cormorant Infant', fontSize: 8, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'B', colNum: 2, fontFamily: 'Cormorant Infant', fontSize: 8, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'C', colNum: 3, fontFamily: 'Cormorant Infant', fontSize: 8, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'D', colNum: 4, fontFamily: 'Cormorant Infant', fontSize: 8, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'E', colNum: 5, fontFamily: 'Cormorant Infant', fontSize: 8, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'F', colNum: 6, fontFamily: 'Cormorant Infant', fontSize: 8, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'G', colNum: 7, fontFamily: 'Roboto Mono', fontSize: 8, italic: true, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'H', colNum: 8, fontFamily: 'Roboto Mono', fontSize: 8, italic: true, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'I', colNum: 9, fontFamily: 'Roboto Mono', fontSize: 10, bold: true, italic: true, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'J', colNum: 10 },
      { col: 'K', colNum: 11 },
      { col: 'L', colNum: 12 },
      { col: 'M', colNum: 13 },
      { col: 'N', colNum: 14 },
    ],
  },
  // Row 7 (Sheet 167): 21px
  {
    row: 167,
    height: 21,
    cells: [
      { col: 'A', colNum: 1, fontFamily: 'Cormorant Infant', fontSize: 30, bold: true, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'B', colNum: 2, fontFamily: 'Cormorant Infant', fontSize: 30, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'C', colNum: 3, fontFamily: 'Cormorant Infant', fontSize: 30, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'D', colNum: 4, fontFamily: 'Cormorant Infant', fontSize: 8, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'E', colNum: 5, fontFamily: 'Cormorant Infant', fontSize: 8, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'F', colNum: 6, fontFamily: 'Cormorant Infant', fontSize: 8, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'G', colNum: 7, fontFamily: 'Roboto Mono', fontSize: 8, italic: true, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'H', colNum: 8, fontFamily: 'Roboto Mono', fontSize: 8, italic: true, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'I', colNum: 9, fontFamily: 'Roboto Mono', fontSize: 10, bold: true, italic: true, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'J', colNum: 10, fontFamily: 'Roboto Mono', fontSize: 10, bold: true, italic: true, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'K', colNum: 11, fontFamily: 'Cormorant Infant', fontSize: 10, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'RIGHT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'L', colNum: 12, fontFamily: 'Cormorant Infant', fontSize: 10, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'RIGHT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'M', colNum: 13, fontFamily: 'Cormorant Infant', fontSize: 10, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'RIGHT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'N', colNum: 14, fontFamily: 'Cormorant Infant', fontSize: 10, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'RIGHT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
    ],
  },
  // Row 8 (Sheet 168): 21px
  {
    row: 168,
    height: 21,
    cells: [
      { col: 'A', colNum: 1, fontFamily: 'Cormorant Infant', fontSize: 8, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'B', colNum: 2, fontFamily: 'Cormorant Infant', fontSize: 8, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'C', colNum: 3, fontFamily: 'Cormorant Infant', fontSize: 8, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'D', colNum: 4, fontFamily: 'Cormorant Infant', fontSize: 8, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'E', colNum: 5, fontFamily: 'Cormorant Infant', fontSize: 8, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'F', colNum: 6, fontFamily: 'Cormorant Infant', fontSize: 8, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'G', colNum: 7, fontFamily: 'Roboto Mono', fontSize: 8, italic: true, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'H', colNum: 8, fontFamily: 'Roboto Mono', fontSize: 8, italic: true, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'I', colNum: 9, fontFamily: 'Roboto Mono', fontSize: 10, bold: true, italic: true, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'J', colNum: 10, fontFamily: 'Roboto Mono', fontSize: 10, bold: true, italic: true, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'K', colNum: 11, fontFamily: 'Cormorant Infant', fontSize: 10, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'RIGHT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'L', colNum: 12, fontFamily: 'Cormorant Infant', fontSize: 10, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'RIGHT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'M', colNum: 13, fontFamily: 'Cormorant Infant', fontSize: 10, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'RIGHT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'N', colNum: 14, fontFamily: 'Cormorant Infant', fontSize: 10, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'RIGHT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
    ],
  },
  // Row 9 (Sheet 169): 21px
  {
    row: 169,
    height: 21,
    cells: [
      { col: 'A', colNum: 1, value: "Payment is due within seven (7) calendar days after the earlier of (i) the invoice date; or (ii) the client’s written request to release final deliverables. Final deliverables are released only after receipt of cleared funds.", fontFamily: 'Cormorant Infant', fontSize: 11, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
      { col: 'B', colNum: 2 },
      { col: 'C', colNum: 3 },
      { col: 'D', colNum: 4 },
      { col: 'E', colNum: 5 },
      { col: 'F', colNum: 6 },
      { col: 'G', colNum: 7 },
      { col: 'H', colNum: 8 },
      { col: 'I', colNum: 9 },
      { col: 'J', colNum: 10 },
      { col: 'K', colNum: 11 },
      { col: 'L', colNum: 12 },
      { col: 'M', colNum: 13 },
      { col: 'N', colNum: 14 },
    ],
  },
  // Row 10 (Sheet 170): 21px
  {
    row: 170,
    height: 21,
    cells: [
      { col: 'A', colNum: 1 },
      { col: 'B', colNum: 2 },
      { col: 'C', colNum: 3 },
      { col: 'D', colNum: 4 },
      { col: 'E', colNum: 5 },
      { col: 'F', colNum: 6 },
      { col: 'G', colNum: 7 },
      { col: 'H', colNum: 8 },
      { col: 'I', colNum: 9 },
      { col: 'J', colNum: 10 },
      { col: 'K', colNum: 11 },
      { col: 'L', colNum: 12 },
      { col: 'M', colNum: 13 },
      { col: 'N', colNum: 14 },
    ],
  },
  // Row 11 (Sheet 171): 21px
  {
    row: 171,
    height: 21,
    cells: [
      { col: 'A', colNum: 1, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
      { col: 'B', colNum: 2, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
      { col: 'C', colNum: 3, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
      { col: 'D', colNum: 4, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
      { col: 'E', colNum: 5, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
      { col: 'F', colNum: 6, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
      { col: 'G', colNum: 7, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
      { col: 'H', colNum: 8, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
      { col: 'I', colNum: 9, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
      { col: 'J', colNum: 10, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
      { col: 'K', colNum: 11, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
      { col: 'L', colNum: 12, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
      { col: 'M', colNum: 13, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
      { col: 'N', colNum: 14, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
    ],
  },
  // Row 12 (Sheet 172): 21px
  {
    row: 172,
    height: 21,
    cells: [
      { col: 'A', colNum: 1, fontFamily: 'Cormorant Infant', fontSize: 12, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'BOTTOM', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'B', colNum: 2, fontFamily: 'Cormorant Infant', fontSize: 8, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'C', colNum: 3, fontFamily: 'Cormorant Infant', fontSize: 8, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'D', colNum: 4, fontFamily: 'Roboto Mono', fontSize: 12, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'MIDDLE', wrapStrategy: 'CLIP' },
      { col: 'E', colNum: 5, fontFamily: 'Roboto Mono', fontSize: 12, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'MIDDLE', wrapStrategy: 'CLIP' },
      { col: 'F', colNum: 6, fontFamily: 'Roboto Mono', fontSize: 12, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'MIDDLE', wrapStrategy: 'CLIP' },
      { col: 'G', colNum: 7, fontFamily: 'Roboto Mono', fontSize: 8, italic: true, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'H', colNum: 8, fontFamily: 'Roboto Mono', fontSize: 8, italic: true, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'I', colNum: 9, fontFamily: 'Roboto Mono', fontSize: 10, bold: true, italic: true, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'J', colNum: 10, fontFamily: 'Roboto Mono', fontSize: 10, bold: true, italic: true, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'K', colNum: 11, fontFamily: 'Cormorant Infant', fontSize: 10, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'RIGHT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'L', colNum: 12, fontFamily: 'Cormorant Infant', fontSize: 10, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'RIGHT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'M', colNum: 13, fontFamily: 'Cormorant Infant', fontSize: 10, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'RIGHT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'N', colNum: 14, fontFamily: 'Cormorant Infant', fontSize: 10, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'RIGHT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
    ],
  },
  // Row 13 (Sheet 173): 29px
  {
    row: 173,
    height: 29,
    cells: [
      { col: 'A', colNum: 1, value: "Beneficiary:", fontFamily: 'Cormorant Infant', fontSize: 10, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'RIGHT', vAlign: 'MIDDLE', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'B', colNum: 2 },
      { col: 'C', colNum: 3 },
      { col: 'D', colNum: 4, value: "<SubsidiaryEnglishName>", fontFamily: 'Federo', fontSize: 15, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'MIDDLE', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'E', colNum: 5 },
      { col: 'F', colNum: 6 },
      { col: 'G', colNum: 7, value: "BR No.:  ", fontFamily: 'Cormorant Infant', fontSize: 10, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'RIGHT', vAlign: 'MIDDLE', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'H', colNum: 8, value: "<SubsidiaryBRNumber>", fontFamily: 'Federo', fontSize: 15, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'MIDDLE', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'I', colNum: 9 },
      { col: 'J', colNum: 10, fontFamily: 'Cormorant Infant', fontSize: 15, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'MIDDLE', wrapStrategy: 'WRAP' },
      { col: 'K', colNum: 11, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
      { col: 'L', colNum: 12, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
      { col: 'M', colNum: 13, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
      { col: 'N', colNum: 14, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
    ],
  },
  // Row 14 (Sheet 174): 29px
  {
    row: 174,
    height: 29,
    cells: [
      { col: 'A', colNum: 1, value: "Bank:", fontFamily: 'Cormorant Infant', fontSize: 10, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'RIGHT', vAlign: 'MIDDLE', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'B', colNum: 2 },
      { col: 'C', colNum: 3 },
      { col: 'D', colNum: 4, value: "<BankName> <BankCode>", fontFamily: 'Federo', fontSize: 15, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'MIDDLE', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'E', colNum: 5 },
      { col: 'F', colNum: 6 },
      { col: 'G', colNum: 7 },
      { col: 'H', colNum: 8 },
      { col: 'I', colNum: 9, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
      { col: 'J', colNum: 10, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
      { col: 'K', colNum: 11, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
      { col: 'L', colNum: 12, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
      { col: 'M', colNum: 13, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
      { col: 'N', colNum: 14, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
    ],
  },
  // Row 15 (Sheet 175): 29px
  {
    row: 175,
    height: 29,
    cells: [
      { col: 'A', colNum: 1, value: "Branch Code:", fontFamily: 'Cormorant Infant', fontSize: 10, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'RIGHT', vAlign: 'MIDDLE', wrapStrategy: 'WRAP' },
      { col: 'B', colNum: 2 },
      { col: 'C', colNum: 3 },
      { col: 'D', colNum: 4, value: "<BankAccountNumberPart1>", fontFamily: 'Federo', fontSize: 15, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'E', colNum: 5, fontFamily: 'Federo', fontSize: 15, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
      { col: 'F', colNum: 6, fontFamily: 'Federo', fontSize: 15, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
      { col: 'G', colNum: 7, value: "Account Number:  ", fontFamily: 'Cormorant Infant', fontSize: 10, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'RIGHT', vAlign: 'MIDDLE', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'H', colNum: 8, value: "<BankAccountNumberPart2>", fontFamily: 'Federo', fontSize: 15, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'MIDDLE', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'I', colNum: 9 },
      { col: 'J', colNum: 10 },
      { col: 'K', colNum: 11 },
      { col: 'L', colNum: 12 },
      { col: 'M', colNum: 13 },
      { col: 'N', colNum: 14, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
    ],
  },
  // Row 16 (Sheet 176): 29px
  {
    row: 176,
    height: 29,
    cells: [
      { col: 'A', colNum: 1, value: "FPS ID:", fontFamily: 'Cormorant Infant', fontSize: 10, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'RIGHT', vAlign: 'MIDDLE', wrapStrategy: 'WRAP' },
      { col: 'B', colNum: 2 },
      { col: 'C', colNum: 3 },
      { col: 'D', colNum: 4, value: "<FPSId>", fontFamily: 'Federo', fontSize: 15, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'MIDDLE', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'E', colNum: 5, fontFamily: 'Federo', fontSize: 15, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'BOTTOM', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'F', colNum: 6, fontFamily: 'Federo', fontSize: 15, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'BOTTOM', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'G', colNum: 7, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
      { col: 'H', colNum: 8, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
      { col: 'I', colNum: 9, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
      { col: 'J', colNum: 10, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
      { col: 'K', colNum: 11, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
      { col: 'L', colNum: 12, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
      { col: 'M', colNum: 13, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
      { col: 'N', colNum: 14, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
    ],
  },
  // Row 17 (Sheet 177): 21px
  {
    row: 177,
    height: 21,
    cells: [
      { col: 'A', colNum: 1, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
      { col: 'B', colNum: 2, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
      { col: 'C', colNum: 3, fontFamily: 'Cormorant Infant', fontSize: 10, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'RIGHT', vAlign: 'MIDDLE', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'D', colNum: 4, fontFamily: 'Federo', fontSize: 15, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'BOTTOM', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'E', colNum: 5, fontFamily: 'Federo', fontSize: 15, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'BOTTOM', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'F', colNum: 6, fontFamily: 'Federo', fontSize: 15, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'BOTTOM', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'G', colNum: 7, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
      { col: 'H', colNum: 8, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
      { col: 'I', colNum: 9, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
      { col: 'J', colNum: 10, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
      { col: 'K', colNum: 11, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
      { col: 'L', colNum: 12, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
      { col: 'M', colNum: 13, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
      { col: 'N', colNum: 14, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
    ],
  },
  // Row 18 (Sheet 178): 21px
  {
    row: 178,
    height: 21,
    cells: [
      { col: 'A', colNum: 1, value: "For the amount of:", fontFamily: 'Cormorant Infant', fontSize: 10, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'RIGHT', vAlign: 'MIDDLE', wrapStrategy: 'WRAP' },
      { col: 'B', colNum: 2 },
      { col: 'C', colNum: 3 },
      { col: 'D', colNum: 4, value: "Five Thousand And Five Hundred Dollars Only", fontFamily: 'Federo', fontSize: 15, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'MIDDLE', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'E', colNum: 5 },
      { col: 'F', colNum: 6 },
      { col: 'G', colNum: 7 },
      { col: 'H', colNum: 8, value: "<SubsidiaryEnglishName>", fontFamily: 'Federo', fontSize: 15, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'MIDDLE', wrapStrategy: 'WRAP' },
      { col: 'I', colNum: 9 },
      { col: 'J', colNum: 10 },
      { col: 'K', colNum: 11 },
      { col: 'L', colNum: 12 },
      { col: 'M', colNum: 13 },
      { col: 'N', colNum: 14, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
    ],
  },
  // Row 19 (Sheet 179): 21px
  {
    row: 179,
    height: 21,
    cells: [
      { col: 'A', colNum: 1 },
      { col: 'B', colNum: 2 },
      { col: 'C', colNum: 3 },
      { col: 'D', colNum: 4 },
      { col: 'E', colNum: 5 },
      { col: 'F', colNum: 6 },
      { col: 'G', colNum: 7 },
      { col: 'H', colNum: 8 },
      { col: 'I', colNum: 9 },
      { col: 'J', colNum: 10 },
      { col: 'K', colNum: 11 },
      { col: 'L', colNum: 12 },
      { col: 'M', colNum: 13 },
      { col: 'N', colNum: 14, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
    ],
  },
  // Row 20 (Sheet 180): 21px
  {
    row: 180,
    height: 21,
    cells: [
      { col: 'A', colNum: 1, value: "茲付金額:", fontFamily: 'Iansui', fontSize: 8, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'RIGHT', vAlign: 'MIDDLE', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'B', colNum: 2 },
      { col: 'C', colNum: 3 },
      { col: 'D', colNum: 4, value: "<InvoiceTotalChinese>", fontFamily: 'Iansui', fontSize: 16, bold: true, textColor: 'rgb(102, 102, 102)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'MIDDLE', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'E', colNum: 5 },
      { col: 'F', colNum: 6 },
      { col: 'G', colNum: 7, value: "Address:", fontFamily: 'Cormorant Infant', fontSize: 10, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'CENTER', vAlign: 'MIDDLE', wrapStrategy: 'WRAP' },
      { col: 'H', colNum: 8, value: "<SubsidiaryAddressLine1>", fontFamily: 'Federo', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'I', colNum: 9 },
      { col: 'J', colNum: 10 },
      { col: 'K', colNum: 11, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
      { col: 'L', colNum: 12, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
      { col: 'M', colNum: 13, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
      { col: 'N', colNum: 14, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
    ],
  },
  // Row 21 (Sheet 181): 21px
  {
    row: 181,
    height: 21,
    cells: [
      { col: 'A', colNum: 1 },
      { col: 'B', colNum: 2 },
      { col: 'C', colNum: 3 },
      { col: 'D', colNum: 4 },
      { col: 'E', colNum: 5 },
      { col: 'F', colNum: 6 },
      { col: 'G', colNum: 7 },
      { col: 'H', colNum: 8, value: "<SubsidiaryAddressLine2>", fontFamily: 'Federo', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'I', colNum: 9, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
      { col: 'J', colNum: 10, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
      { col: 'K', colNum: 11, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
      { col: 'L', colNum: 12, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
      { col: 'M', colNum: 13, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
      { col: 'N', colNum: 14, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
    ],
  },
  // Row 22 (Sheet 182): 21px
  {
    row: 182,
    height: 21,
    cells: [
      { col: 'A', colNum: 1, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
      { col: 'B', colNum: 2, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
      { col: 'C', colNum: 3, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
      { col: 'D', colNum: 4, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
      { col: 'E', colNum: 5, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
      { col: 'F', colNum: 6, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
      { col: 'G', colNum: 7, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
      { col: 'H', colNum: 8, value: "<SubsidiaryAddressLine3>", fontFamily: 'Federo', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'I', colNum: 9, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
      { col: 'J', colNum: 10, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
      { col: 'K', colNum: 11, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
      { col: 'L', colNum: 12, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
      { col: 'M', colNum: 13, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
      { col: 'N', colNum: 14, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
    ],
  },
  // Row 23 (Sheet 183): 21px
  {
    row: 183,
    height: 21,
    cells: [
      { col: 'A', colNum: 1, fontFamily: 'Cormorant Infant', fontSize: 12, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'BOTTOM', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'B', colNum: 2, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
      { col: 'C', colNum: 3, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'RIGHT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
      { col: 'D', colNum: 4, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
      { col: 'E', colNum: 5, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
      { col: 'F', colNum: 6, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
      { col: 'G', colNum: 7, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
      { col: 'H', colNum: 8, value: "<SubsidiaryRegion>, Hong Kong", fontFamily: 'Federo', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'I', colNum: 9, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
      { col: 'J', colNum: 10, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
      { col: 'K', colNum: 11, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
      { col: 'L', colNum: 12, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
      { col: 'M', colNum: 13, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
      { col: 'N', colNum: 14, fontFamily: 'Cormorant Infant', fontSize: 10, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'WRAP' },
    ],
  },
  // Row 24 (Sheet 184): 21px
  {
    row: 184,
    height: 21,
    cells: [
      { col: 'A', colNum: 1, fontFamily: 'Cormorant Infant', fontSize: 10, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'BOTTOM', wrapStrategy: 'WRAP' },
      { col: 'B', colNum: 2, fontFamily: 'Cormorant Infant', fontSize: 10, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'BOTTOM', wrapStrategy: 'WRAP' },
      { col: 'C', colNum: 3, fontFamily: 'Cormorant Infant', fontSize: 10, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'BOTTOM', wrapStrategy: 'WRAP' },
      { col: 'D', colNum: 4, fontFamily: 'Cormorant Infant', fontSize: 10, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'BOTTOM', wrapStrategy: 'WRAP' },
      { col: 'E', colNum: 5, fontFamily: 'Cormorant Infant', fontSize: 10, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'BOTTOM', wrapStrategy: 'WRAP' },
      { col: 'F', colNum: 6, fontFamily: 'Cormorant Infant', fontSize: 10, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'BOTTOM', wrapStrategy: 'WRAP' },
      { col: 'G', colNum: 7, fontFamily: 'Cormorant Infant', fontSize: 10, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'BOTTOM', wrapStrategy: 'WRAP' },
      { col: 'H', colNum: 8, fontFamily: 'Cormorant Infant', fontSize: 10, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'BOTTOM', wrapStrategy: 'WRAP' },
      { col: 'I', colNum: 9, fontFamily: 'Cormorant Infant', fontSize: 10, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'BOTTOM', wrapStrategy: 'WRAP' },
      { col: 'J', colNum: 10, fontFamily: 'Cormorant Infant', fontSize: 10, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'BOTTOM', wrapStrategy: 'WRAP' },
      { col: 'K', colNum: 11, fontFamily: 'Cormorant Infant', fontSize: 10, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'BOTTOM', wrapStrategy: 'WRAP' },
      { col: 'L', colNum: 12, fontFamily: 'Cormorant Infant', fontSize: 10, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'BOTTOM', wrapStrategy: 'WRAP' },
      { col: 'M', colNum: 13, fontFamily: 'Cormorant Infant', fontSize: 10, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'BOTTOM', wrapStrategy: 'WRAP' },
      { col: 'N', colNum: 14, fontFamily: 'Cormorant Infant', fontSize: 10, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'BOTTOM', wrapStrategy: 'WRAP' },
    ],
  },
  // Row 25 (Sheet 185): 21px
  {
    row: 185,
    height: 21,
    cells: [
      { col: 'A', colNum: 1, value: "FPS QR Code:  ", fontFamily: 'Cormorant Infant', fontSize: 11, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'RIGHT', vAlign: 'BOTTOM', wrapStrategy: 'WRAP' },
      { col: 'B', colNum: 2 },
      { col: 'C', colNum: 3 },
      { col: 'D', colNum: 4, value: "<FPSQRCode>", fontFamily: 'Roboto Mono', fontSize: 12, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'CENTER', vAlign: 'MIDDLE', wrapStrategy: 'CLIP' },
      { col: 'E', colNum: 5 },
      { col: 'F', colNum: 6, fontFamily: 'Roboto Mono', fontSize: 12, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'MIDDLE', wrapStrategy: 'CLIP' },
      { col: 'G', colNum: 7, fontFamily: 'Roboto Mono', fontSize: 12, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'MIDDLE', wrapStrategy: 'CLIP' },
      { col: 'H', colNum: 8, fontFamily: 'Roboto Mono', fontSize: 12, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'MIDDLE', wrapStrategy: 'CLIP' },
      { col: 'I', colNum: 9, fontFamily: 'Roboto Mono', fontSize: 12, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'MIDDLE', wrapStrategy: 'CLIP' },
      { col: 'J', colNum: 10, fontFamily: 'Roboto Mono', fontSize: 12, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'MIDDLE', wrapStrategy: 'CLIP' },
      { col: 'K', colNum: 11, fontFamily: 'Roboto Mono', fontSize: 12, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'MIDDLE', wrapStrategy: 'CLIP' },
      { col: 'L', colNum: 12, fontFamily: 'Roboto Mono', fontSize: 12, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'MIDDLE', wrapStrategy: 'CLIP' },
      { col: 'M', colNum: 13, fontFamily: 'Roboto Mono', fontSize: 12, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'MIDDLE', wrapStrategy: 'CLIP' },
      { col: 'N', colNum: 14, fontFamily: 'Roboto Mono', fontSize: 12, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'MIDDLE', wrapStrategy: 'CLIP' },
    ],
  },
  // Row 26 (Sheet 186): 77px
  {
    row: 186,
    height: 77,
    cells: [
      { col: 'A', colNum: 1, fontFamily: 'Cormorant Infant', fontSize: 10, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'BOTTOM', wrapStrategy: 'WRAP' },
      { col: 'B', colNum: 2, fontFamily: 'Cormorant Infant', fontSize: 10, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'BOTTOM', wrapStrategy: 'WRAP' },
      { col: 'C', colNum: 3, fontFamily: 'Cormorant Infant', fontSize: 10, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'BOTTOM', wrapStrategy: 'WRAP' },
      { col: 'D', colNum: 4 },
      { col: 'E', colNum: 5 },
      { col: 'F', colNum: 6, value: "This QR code is compatible only with bank or e-wallet apps that support FPS merchant-presented QR code; if your bank’s app does not offer a scan-to-pay function, please make a manual transfer using the payment details on this invoice and include the invoice number as the payment reference.", fontFamily: 'Cormorant Infant', fontSize: 11, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'BOTTOM', wrapStrategy: 'WRAP' },
      { col: 'G', colNum: 7 },
      { col: 'H', colNum: 8 },
      { col: 'I', colNum: 9 },
      { col: 'J', colNum: 10 },
      { col: 'K', colNum: 11 },
      { col: 'L', colNum: 12 },
      { col: 'M', colNum: 13 },
      { col: 'N', colNum: 14 },
    ],
  },
  // Row 27 (Sheet 187): 21px
  {
    row: 187,
    height: 21,
    cells: [
      { col: 'A', colNum: 1, fontFamily: 'Cormorant Infant', fontSize: 12, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'BOTTOM', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'B', colNum: 2, fontFamily: 'Cormorant Infant', fontSize: 8, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'C', colNum: 3, fontFamily: 'Cormorant Infant', fontSize: 8, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'D', colNum: 4 },
      { col: 'E', colNum: 5 },
      { col: 'F', colNum: 6, fontFamily: 'Roboto Mono', fontSize: 12, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'MIDDLE', wrapStrategy: 'CLIP' },
      { col: 'G', colNum: 7, fontFamily: 'Roboto Mono', fontSize: 8, italic: true, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'H', colNum: 8, fontFamily: 'Roboto Mono', fontSize: 8, italic: true, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'I', colNum: 9, fontFamily: 'Roboto Mono', fontSize: 10, bold: true, italic: true, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'J', colNum: 10, fontFamily: 'Roboto Mono', fontSize: 10, bold: true, italic: true, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'K', colNum: 11, fontFamily: 'Cormorant Infant', fontSize: 10, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'RIGHT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'L', colNum: 12, fontFamily: 'Cormorant Infant', fontSize: 10, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'RIGHT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'M', colNum: 13, fontFamily: 'Cormorant Infant', fontSize: 10, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'RIGHT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'N', colNum: 14, fontFamily: 'Cormorant Infant', fontSize: 10, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'RIGHT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
    ],
  },
  // Row 28 (Sheet 188): 21px
  {
    row: 188,
    height: 21,
    cells: [
      { col: 'A', colNum: 1, fontFamily: 'Cormorant Infant', fontSize: 12, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'BOTTOM', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'B', colNum: 2, fontFamily: 'Cormorant Infant', fontSize: 8, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'C', colNum: 3, fontFamily: 'Cormorant Infant', fontSize: 8, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'D', colNum: 4, fontFamily: 'Roboto Mono', fontSize: 12, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'MIDDLE', wrapStrategy: 'CLIP' },
      { col: 'E', colNum: 5, fontFamily: 'Roboto Mono', fontSize: 12, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'MIDDLE', wrapStrategy: 'CLIP' },
      { col: 'F', colNum: 6, fontFamily: 'Roboto Mono', fontSize: 12, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'MIDDLE', wrapStrategy: 'CLIP' },
      { col: 'G', colNum: 7, fontFamily: 'Roboto Mono', fontSize: 8, italic: true, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'H', colNum: 8, fontFamily: 'Roboto Mono', fontSize: 8, italic: true, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'I', colNum: 9, fontFamily: 'Roboto Mono', fontSize: 10, bold: true, italic: true, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'J', colNum: 10, fontFamily: 'Roboto Mono', fontSize: 10, bold: true, italic: true, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'K', colNum: 11, fontFamily: 'Cormorant Infant', fontSize: 10, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'RIGHT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'L', colNum: 12, fontFamily: 'Cormorant Infant', fontSize: 10, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'RIGHT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'M', colNum: 13, fontFamily: 'Cormorant Infant', fontSize: 10, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'RIGHT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'N', colNum: 14, fontFamily: 'Cormorant Infant', fontSize: 10, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'RIGHT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
    ],
  },
  // Row 29 (Sheet 189): 21px
  {
    row: 189,
    height: 21,
    cells: [
      { col: 'A', colNum: 1, fontFamily: 'Cormorant Infant', fontSize: 11, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'BOTTOM', wrapStrategy: 'WRAP' },
      { col: 'B', colNum: 2, fontFamily: 'Cormorant Infant', fontSize: 11, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'BOTTOM', wrapStrategy: 'WRAP' },
      { col: 'C', colNum: 3, fontFamily: 'Cormorant Infant', fontSize: 11, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'BOTTOM', wrapStrategy: 'WRAP' },
      { col: 'D', colNum: 4, fontFamily: 'Cormorant Infant', fontSize: 11, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'BOTTOM', wrapStrategy: 'WRAP' },
      { col: 'E', colNum: 5, fontFamily: 'Cormorant Infant', fontSize: 11, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'BOTTOM', wrapStrategy: 'WRAP' },
      { col: 'F', colNum: 6, fontFamily: 'Cormorant Infant', fontSize: 11, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'BOTTOM', wrapStrategy: 'WRAP' },
      { col: 'G', colNum: 7, fontFamily: 'Cormorant Infant', fontSize: 11, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'BOTTOM', wrapStrategy: 'WRAP' },
      { col: 'H', colNum: 8, fontFamily: 'Cormorant Infant', fontSize: 11, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'BOTTOM', wrapStrategy: 'WRAP' },
      { col: 'I', colNum: 9, fontFamily: 'Cormorant Infant', fontSize: 11, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'BOTTOM', wrapStrategy: 'WRAP' },
      { col: 'J', colNum: 10, fontFamily: 'Cormorant Infant', fontSize: 11, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'BOTTOM', wrapStrategy: 'WRAP' },
      { col: 'K', colNum: 11, fontFamily: 'Cormorant Infant', fontSize: 11, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'BOTTOM', wrapStrategy: 'WRAP' },
      { col: 'L', colNum: 12, fontFamily: 'Cormorant Infant', fontSize: 11, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'BOTTOM', wrapStrategy: 'WRAP' },
      { col: 'M', colNum: 13, fontFamily: 'Cormorant Infant', fontSize: 11, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'BOTTOM', wrapStrategy: 'WRAP' },
      { col: 'N', colNum: 14, fontFamily: 'Cormorant Infant', fontSize: 11, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'BOTTOM', wrapStrategy: 'WRAP' },
    ],
  },
  // Row 30 (Sheet 190): 21px
  {
    row: 190,
    height: 21,
    cells: [
      { col: 'A', colNum: 1, fontFamily: 'Iansui', fontSize: 9, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'BOTTOM', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'B', colNum: 2, fontFamily: 'Cormorant Infant', fontSize: 8, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'C', colNum: 3, fontFamily: 'Cormorant Infant', fontSize: 8, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'D', colNum: 4, fontFamily: 'Cormorant Infant', fontSize: 8, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'E', colNum: 5, fontFamily: 'Cormorant Infant', fontSize: 8, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'F', colNum: 6, fontFamily: 'Cormorant Infant', fontSize: 8, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'G', colNum: 7, fontFamily: 'Roboto Mono', fontSize: 8, italic: true, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'H', colNum: 8, fontFamily: 'Roboto Mono', fontSize: 8, italic: true, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'I', colNum: 9, fontFamily: 'Roboto Mono', fontSize: 10, bold: true, italic: true, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'J', colNum: 10, fontFamily: 'Roboto Mono', fontSize: 10, bold: true, italic: true, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'K', colNum: 11, fontFamily: 'Cormorant Infant', fontSize: 10, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'RIGHT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'L', colNum: 12, fontFamily: 'Cormorant Infant', fontSize: 10, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'RIGHT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'M', colNum: 13, fontFamily: 'Cormorant Infant', fontSize: 10, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'RIGHT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'N', colNum: 14, fontFamily: 'Cormorant Infant', fontSize: 10, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'RIGHT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
    ],
  },
  // Row 31 (Sheet 191): 26px
  {
    row: 191,
    height: 26,
    cells: [
      { col: 'A', colNum: 1, value: "Your prompt payment will be appreciated, thank you for your business.", fontFamily: 'Cormorant Infant', fontSize: 13, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'BOTTOM', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'B', colNum: 2 },
      { col: 'C', colNum: 3 },
      { col: 'D', colNum: 4 },
      { col: 'E', colNum: 5 },
      { col: 'F', colNum: 6 },
      { col: 'G', colNum: 7 },
      { col: 'H', colNum: 8 },
      { col: 'I', colNum: 9 },
      { col: 'J', colNum: 10 },
      { col: 'K', colNum: 11 },
      { col: 'L', colNum: 12 },
      { col: 'M', colNum: 13 },
      { col: 'N', colNum: 14 },
    ],
  },
  // Row 32 (Sheet 192): 21px
  {
    row: 192,
    height: 21,
    cells: [
      { col: 'A', colNum: 1 },
      { col: 'B', colNum: 2 },
      { col: 'C', colNum: 3 },
      { col: 'D', colNum: 4 },
      { col: 'E', colNum: 5 },
      { col: 'F', colNum: 6 },
      { col: 'G', colNum: 7 },
      { col: 'H', colNum: 8 },
      { col: 'I', colNum: 9 },
      { col: 'J', colNum: 10 },
      { col: 'K', colNum: 11 },
      { col: 'L', colNum: 12 },
      { col: 'M', colNum: 13 },
      { col: 'N', colNum: 14 },
    ],
  },
  // Row 33 (Sheet 193): 21px
  {
    row: 193,
    height: 21,
    cells: [
      { col: 'A', colNum: 1 },
      { col: 'B', colNum: 2 },
      { col: 'C', colNum: 3 },
      { col: 'D', colNum: 4 },
      { col: 'E', colNum: 5 },
      { col: 'F', colNum: 6 },
      { col: 'G', colNum: 7 },
      { col: 'H', colNum: 8 },
      { col: 'I', colNum: 9 },
      { col: 'J', colNum: 10 },
      { col: 'K', colNum: 11 },
      { col: 'L', colNum: 12 },
      { col: 'M', colNum: 13 },
      { col: 'N', colNum: 14 },
    ],
  },
  // Row 34 (Sheet 194): 21px
  {
    row: 194,
    height: 21,
    cells: [
      { col: 'A', colNum: 1 },
      { col: 'B', colNum: 2 },
      { col: 'C', colNum: 3 },
      { col: 'D', colNum: 4 },
      { col: 'E', colNum: 5 },
      { col: 'F', colNum: 6 },
      { col: 'G', colNum: 7 },
      { col: 'H', colNum: 8 },
      { col: 'I', colNum: 9 },
      { col: 'J', colNum: 10 },
      { col: 'K', colNum: 11 },
      { col: 'L', colNum: 12 },
      { col: 'M', colNum: 13 },
      { col: 'N', colNum: 14 },
    ],
  },
  // Row 35 (Sheet 195): 21px
  {
    row: 195,
    height: 21,
    cells: [
      { col: 'A', colNum: 1, value: "Terms & Conditions", fontFamily: 'Cormorant Infant', fontSize: 9, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'BOTTOM', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'B', colNum: 2 },
      { col: 'C', colNum: 3 },
      { col: 'D', colNum: 4 },
      { col: 'E', colNum: 5 },
      { col: 'F', colNum: 6 },
      { col: 'G', colNum: 7 },
      { col: 'H', colNum: 8 },
      { col: 'I', colNum: 9 },
      { col: 'J', colNum: 10 },
      { col: 'K', colNum: 11 },
      { col: 'L', colNum: 12 },
      { col: 'M', colNum: 13 },
      { col: 'N', colNum: 14 },
    ],
  },
  // Row 36 (Sheet 196): 161px
  {
    row: 196,
    height: 161,
    cells: [
      { col: 'A', colNum: 1, value: "1.  Acceptance. By continuing to use our services, instructing us to proceed, requesting release of deliverables, failing to object in writing within the dispute period, or paying in whole or in part, the Client is deemed to have agreed to and be bound by these Terms & Conditions. \n2.  Payment Due. Payment is due within seven (7) days after the earlier of (i) the Invoice date; or (ii) the Client’s written request to release final deliverables. Final deliverables will be released only after cleared funds (credited to our designated account) are received. \n3.  Disputes. Any billing disputes must be submitted in writing within three (3) days of receipt of this Invoice; otherwise, the Invoice is deemed accepted. \n4.  Late Charges. If payment is not received when due, a late fee of the greater of HK$150 or 1.5% of the outstanding balance for each 14-day period (or any part thereof) will accrue from the due date until paid in full, unless otherwise agreed in writing. \n5.  Carry-Forward. Accrued late charges (and reasonable collection costs) may be carried forward and added to the Client’s next invoice or project, to the extent permitted by law, without prejudice to any other rights or remedies. \n6.  Suspension / Withholding. We may suspend services and/or withhold deliverables (including current or future projects) while any amount remains unpaid. \n7.  Currency & Fees. Unless stated otherwise, all amounts are in HKD. Bank/remittance charges are for the payer’s account; the net amount received must equal the Invoice total. \n8.  Application of Payments. Unless otherwise agreed in writing, we may apply payments to the oldest outstanding amounts first.", fontFamily: 'Cormorant Infant', fontSize: 8, textColor: 'rgb(102, 102, 102)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'MIDDLE', wrapStrategy: 'WRAP', textRuns: [{"startIndex":0,"format":{}},{"startIndex":4,"format":{"bold":true}},{"startIndex":15,"format":{}},{"startIndex":287,"format":{"bold":true}},{"startIndex":299,"format":{}},{"startIndex":565,"format":{"bold":true}},{"startIndex":574,"format":{}},{"startIndex":723,"format":{"bold":true}},{"startIndex":736,"format":{}},{"startIndex":981,"format":{"bold":true}},{"startIndex":995,"format":{}},{"startIndex":1213,"format":{"bold":true}},{"startIndex":1238,"format":{}},{"startIndex":1369,"format":{"bold":true}},{"startIndex":1385,"format":{}},{"startIndex":1547,"format":{"bold":true}},{"startIndex":1571,"format":{}}] },
      { col: 'B', colNum: 2 },
      { col: 'C', colNum: 3 },
      { col: 'D', colNum: 4 },
      { col: 'E', colNum: 5 },
      { col: 'F', colNum: 6 },
      { col: 'G', colNum: 7 },
      { col: 'H', colNum: 8 },
      { col: 'I', colNum: 9 },
      { col: 'J', colNum: 10 },
      { col: 'K', colNum: 11 },
      { col: 'L', colNum: 12 },
      { col: 'M', colNum: 13 },
      { col: 'N', colNum: 14 },
    ],
  },
  // Row 37 (Sheet 197): 21px
  {
    row: 197,
    height: 21,
    cells: [
      { col: 'A', colNum: 1, value: "條款及細則", fontFamily: 'Yuji Mai', fontSize: 8, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'BOTTOM', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'B', colNum: 2 },
      { col: 'C', colNum: 3 },
      { col: 'D', colNum: 4 },
      { col: 'E', colNum: 5 },
      { col: 'F', colNum: 6 },
      { col: 'G', colNum: 7 },
      { col: 'H', colNum: 8 },
      { col: 'I', colNum: 9 },
      { col: 'J', colNum: 10 },
      { col: 'K', colNum: 11 },
      { col: 'L', colNum: 12 },
      { col: 'M', colNum: 13 },
      { col: 'N', colNum: 14 },
    ],
  },
  // Row 38 (Sheet 198): 115px
  {
    row: 198,
    height: 115,
    cells: [
      { col: 'A', colNum: 1, value: "1.  同意與約束力。 客戶如繼續使用本公司服務、指示本公司開展／續行工作、要求發放交付品、於爭議期限內未以書面提出異議，或已全部或部分付款，即視為已同意並受本條款及細則約束。 \n2.  到期付款。 付款須於以下二者中之較早者起計七（7）日內繳清：（i）發票日期；或（ii）客戶以書面要求發放最終交付品之日期。最終交付品將於款項已入賬（存入本公司指定賬戶）後方予發放。 \n3.  爭議。 任何賬單爭議須於收妥本發票後三（3）日內以書面提出；逾期視為已接納本發票。 \n4.  逾期費用。 如未如期付款，將就每一個十四（14）日期（不足十四日亦作一個期計）按較高者收取：港幣一百五十元（HK$150）或欠款金額之1.5%，由到期日起累計至全數清償為止；除非另有書面協議。 \n5.  結轉。 在法律許可範圍內，累積之逾期費用（及合理之追收成本）可結轉並列入同一客戶之下一張發票或下一個項目，並不影響本公司之其他權利或補救。 \n6.  暫停／扣留。 於任何金額未清償期間，本公司可暫停提供服務及／或扣留交付品（包括現行或未來項目）。 \n7.  貨幣及手續費。 除另有說明，所有金額以**港幣（HKD）**計算；銀行╱匯款手續費由付款人承擔，並須確保本公司實收淨額等同發票金額。 \n8.  付款抵銷次序。 除另有書面約定，本公司可將所收款項優先抵銷最早到期之未清款項。", fontFamily: 'Iansui', fontSize: 7, textColor: 'rgb(102, 102, 102)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'MIDDLE', wrapStrategy: 'WRAP', textRuns: [{"startIndex":0,"format":{}},{"startIndex":4,"format":{"fontFamily":"Yuji Mai","bold":true}},{"startIndex":11,"format":{}},{"startIndex":94,"format":{"fontFamily":"Yuji Mai","bold":true}},{"startIndex":99,"format":{}},{"startIndex":190,"format":{"fontFamily":"Yuji Mai","bold":true}},{"startIndex":193,"format":{}},{"startIndex":237,"format":{"fontFamily":"Yuji Mai","bold":true}},{"startIndex":242,"format":{}},{"startIndex":339,"format":{"fontFamily":"Yuji Mai","bold":true}},{"startIndex":342,"format":{}},{"startIndex":414,"format":{"fontFamily":"Yuji Mai","bold":true}},{"startIndex":420,"format":{}},{"startIndex":468,"format":{"fontFamily":"Yuji Mai","bold":true}},{"startIndex":475,"format":{}},{"startIndex":540,"format":{"fontFamily":"Yuji Mai","bold":true}},{"startIndex":547,"format":{}}] },
      { col: 'B', colNum: 2 },
      { col: 'C', colNum: 3 },
      { col: 'D', colNum: 4 },
      { col: 'E', colNum: 5 },
      { col: 'F', colNum: 6 },
      { col: 'G', colNum: 7 },
      { col: 'H', colNum: 8 },
      { col: 'I', colNum: 9 },
      { col: 'J', colNum: 10 },
      { col: 'K', colNum: 11 },
      { col: 'L', colNum: 12 },
      { col: 'M', colNum: 13 },
      { col: 'N', colNum: 14 },
    ],
  },
  // Row 39 (Sheet 199): 21px
  {
    row: 199,
    height: 21,
    cells: [
      { col: 'A', colNum: 1 },
      { col: 'B', colNum: 2 },
      { col: 'C', colNum: 3 },
      { col: 'D', colNum: 4 },
      { col: 'E', colNum: 5 },
      { col: 'F', colNum: 6 },
      { col: 'G', colNum: 7 },
      { col: 'H', colNum: 8 },
      { col: 'I', colNum: 9 },
      { col: 'J', colNum: 10 },
      { col: 'K', colNum: 11 },
      { col: 'L', colNum: 12 },
      { col: 'M', colNum: 13 },
      { col: 'N', colNum: 14 },
    ],
  },
  // Row 40 (Sheet 200): 24px
  {
    row: 200,
    height: 24,
    cells: [
      { col: 'A', colNum: 1, value: "<SubsidiaryEnglishName>", fontFamily: 'Cormorant Infant', fontSize: 12, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'BOTTOM', wrapStrategy: 'OVERFLOW_CELL', borders: {"top":{"style":"SOLID","width":1,"color":"rgb(239, 239, 239)"}} },
      { col: 'B', colNum: 2 },
      { col: 'C', colNum: 3 },
      { col: 'D', colNum: 4 },
      { col: 'E', colNum: 5, fontFamily: 'Cormorant Infant', fontSize: 12, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'BOTTOM', wrapStrategy: 'OVERFLOW_CELL', borders: {"top":{"style":"SOLID","width":1,"color":"rgb(239, 239, 239)"}} },
      { col: 'F', colNum: 6, fontFamily: 'Cormorant Infant', fontSize: 12, bold: true, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'BOTTOM', wrapStrategy: 'OVERFLOW_CELL', borders: {"top":{"style":"SOLID","width":1,"color":"rgb(239, 239, 239)"}} },
      { col: 'G', colNum: 7, fontFamily: 'arial,sans,sans-serif', fontSize: 10, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'BOTTOM', wrapStrategy: 'OVERFLOW_CELL', borders: {"top":{"style":"SOLID","width":1,"color":"rgb(239, 239, 239)"}} },
      { col: 'H', colNum: 8, fontFamily: 'arial,sans,sans-serif', fontSize: 10, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'BOTTOM', wrapStrategy: 'OVERFLOW_CELL', borders: {"top":{"style":"SOLID","width":1,"color":"rgb(239, 239, 239)"}} },
      { col: 'I', colNum: 9, fontFamily: 'arial,sans,sans-serif', fontSize: 10, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'BOTTOM', wrapStrategy: 'OVERFLOW_CELL', borders: {"top":{"style":"SOLID","width":1,"color":"rgb(239, 239, 239)"}} },
      { col: 'J', colNum: 10, fontFamily: 'arial,sans,sans-serif', fontSize: 10, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'BOTTOM', wrapStrategy: 'OVERFLOW_CELL', borders: {"top":{"style":"SOLID","width":1,"color":"rgb(239, 239, 239)"}} },
      { col: 'K', colNum: 11, fontFamily: 'arial,sans,sans-serif', fontSize: 10, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'BOTTOM', wrapStrategy: 'OVERFLOW_CELL', borders: {"top":{"style":"SOLID","width":1,"color":"rgb(239, 239, 239)"}} },
      { col: 'L', colNum: 12, fontFamily: 'arial,sans,sans-serif', fontSize: 10, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'BOTTOM', wrapStrategy: 'OVERFLOW_CELL', borders: {"top":{"style":"SOLID","width":1,"color":"rgb(239, 239, 239)"}} },
      { col: 'M', colNum: 13, fontFamily: 'arial,sans,sans-serif', fontSize: 10, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'BOTTOM', wrapStrategy: 'OVERFLOW_CELL', borders: {"top":{"style":"SOLID","width":1,"color":"rgb(239, 239, 239)"}} },
      { col: 'N', colNum: 14, fontFamily: 'arial,sans,sans-serif', fontSize: 10, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'BOTTOM', wrapStrategy: 'OVERFLOW_CELL', borders: {"top":{"style":"SOLID","width":1,"color":"rgb(239, 239, 239)"}} },
    ],
  },
  // Row 41 (Sheet 201): 57px
  {
    row: 201,
    height: 57,
    cells: [
      { col: 'A', colNum: 1, value: "<SubsidiaryAddressLine1> \n<SubsidiaryAddressLine2> \\n                    \n<SubsidiaryAddressLine3> \\n              \n<SubsidiaryRegion>, Hong Kong                        ", fontFamily: 'Cormorant Infant', fontSize: 8, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'MIDDLE', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'B', colNum: 2 },
      { col: 'C', colNum: 3 },
      { col: 'D', colNum: 4 },
      { col: 'E', colNum: 5, fontFamily: 'Cormorant Infant', fontSize: 8, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'F', colNum: 6, fontFamily: 'Cormorant Infant', fontSize: 8, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'G', colNum: 7, fontFamily: 'arial,sans,sans-serif', fontSize: 10, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'H', colNum: 8, fontFamily: 'arial,sans,sans-serif', fontSize: 10, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'I', colNum: 9, fontFamily: 'arial,sans,sans-serif', fontSize: 10, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'J', colNum: 10, fontFamily: 'arial,sans,sans-serif', fontSize: 10, backgroundColor: 'rgb(255, 255, 255)', hAlign: 'LEFT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'K', colNum: 11, value: "<SubsidiaryPhone> *Spacified* \n<SubsidiaryEmail> *Spacified*\n", fontFamily: 'Cormorant Infant', fontSize: 10, textColor: 'rgb(67, 67, 67)', backgroundColor: 'rgb(255, 255, 255)', hAlign: 'RIGHT', vAlign: 'TOP', wrapStrategy: 'OVERFLOW_CELL' },
      { col: 'L', colNum: 12 },
      { col: 'M', colNum: 13 },
      { col: 'N', colNum: 14 },
    ],
  },
];
