steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/next-app', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/next-app']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - next-app
      - --image=gcr.io/$PROJECT_ID/next-app
      - --region=us-central1
      - --platform=managed
      - --quiet
      - --allow-unauthenticated
images:
  - 'gcr.io/$PROJECT_ID/next-app'
