steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/aote-pms/aote-pms:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/aote-pms/aote-pms:latest']
images:
  - 'gcr.io/aote-pms/aote-pms:latest'
