steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/aote-pms/cloud-run-source-deploy/api-service:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/aote-pms/cloud-run-source-deploy/api-service:latest']
images:
  - 'us-central1-docker.pkg.dev/aote-pms/cloud-run-source-deploy/api-service:latest'
