name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: ci-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  node-ci:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect package manager
        id: pm
        run: |
          if [ -f pnpm-lock.yaml ]; then echo "mgr=pnpm" >> $GITHUB_OUTPUT;
          elif [ -f yarn.lock ]; then echo "mgr=yarn" >> $GITHUB_OUTPUT;
          else echo "mgr=npm" >> $GITHUB_OUTPUT; fi

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: ${{ steps.pm.outputs.mgr }}

      - name: Install
        run: |
          if [ "${{ steps.pm.outputs.mgr }}" = "pnpm" ]; then corepack enable pnpm && pnpm install --frozen-lockfile;
          elif [ "${{ steps.pm.outputs.mgr }}" = "yarn" ]; then yarn --frozen-lockfile;
          else npm ci; fi

      - name: Lint
        run: |
          if [ -f package.json ] && jq -e '.scripts.lint' package.json >/dev/null 2>&1; then
            ${{ steps.pm.outputs.mgr }} run lint
          else
            echo "No lint script; skipping."
          fi

      - name: Typecheck
        run: |
          if [ -f tsconfig.json ] && jq -e '.scripts.typecheck' package.json >/dev/null 2>&1; then
            ${{ steps.pm.outputs.mgr }} run typecheck
          else
            echo "No typecheck script; skipping."
          fi

      - name: Build
        run: |
          if jq -e '.scripts.build' package.json >/dev/null 2>&1; then
            ${{ steps.pm.outputs.mgr }} run build
          else
            echo "No build script; skipping."
          fi

      - name: Upload build artifact (optional)
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            .next
            dist
          if-no-files-found: ignore
