name: Context Bundle (Branch)

on:
  push:
    branches:
      - "**"
    # Optional: ignore main if you only want this for feature branches
    # branches-ignore:
    #   - main
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  bundle:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    concurrency:
      # Use sanitized branch in concurrency group to avoid slashes here too
      group: context-bundle-branch-${{ github.ref_name || github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Compute refs
        id: refs
        shell: bash
        run: |
          echo "BRANCH_NAME=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
          echo "SANITIZED_BRANCH_NAME=${GITHUB_REF_NAME//\//-}" >> $GITHUB_OUTPUT
          echo "SHA=${GITHUB_SHA}" >> $GITHUB_OUTPUT
          # Compare against main; adjust if your default branch differs
          git fetch origin main --depth=1 || true
          echo "BASE_REF=origin/main" >> $GITHUB_OUTPUT

      - name: Generate bundle
        shell: bash
        run: |
          BASE="${{ steps.refs.outputs.BASE_REF }}"
          HEAD="${{ steps.refs.outputs.SHA }}"

          echo "# Context Bundle (Branch)" > bundle.md
          echo >> bundle.md
          echo "_Branch_: ${{ steps.refs.outputs.BRANCH_NAME }}  |  _SHA_: ${HEAD}" >> bundle.md
          echo "_Generated_: $(date -u '+%Y-%m-%d %H:%M UTC')" >> bundle.md
          echo >> bundle.md
          echo "### Changed Files (vs main)" >> bundle.md
          git diff --name-status "$BASE" "$HEAD" > files.txt || true
          if [ -s files.txt ]; then
            awk '{print "- " $0}' files.txt >> bundle.md
          else
            echo "_No diff vs main (new branch or no changes)_" >> bundle.md
          fi
          echo >> bundle.md
          echo "### Compact Diff Hunks" >> bundle.md
          echo >> bundle.md
          git diff --unified=0 "$BASE" "$HEAD" | head -n 3000 > hunks.patch || true
          if [ -s hunks.patch ]; then
            echo '```diff' >> bundle.md
            cat hunks.patch >> bundle.md
            echo '```' >> bundle.md
          else
            echo "_(empty)_" >> bundle.md
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          # ✅ Slash-safe artifact name
          name: context-bundle-branch-${{ steps.refs.outputs.SANITIZED_BRANCH_NAME }}
          path: |
            bundle.md
            files.txt
            hunks.patch
          if-no-files-found: ignore
