name: Deploy Codex PR to Vercel Production

on:
  push:
    branches:
      - main
      - shwdtf-*          # your Codex PRs
      - codex/*           # additional Codex-style branches
    # BLACKLIST ONLY: if a push changes ONLY these paths, the job won't run
    paths-ignore:
      - 'docs/**'
      - 'prompts/**'
      - '.github/**'      # editing workflows should NOT deploy your app
      - '**/*.md'         # any markdown-only change (README, etc.)

  # keep manual runs available (optional)
  workflow_dispatch: {}

permissions:
  contents: read
  deployments: write

concurrency:
  group: vercel-prod-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Install Vercel CLI
        run: npm i -g vercel@latest

      # Pull environment (Production)
      - name: Link Vercel project (prod)
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      # Build locally using Vercel build (produces .vercel/output)
      - name: Build
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      # Deploy the prebuilt output as Production
      - name: Deploy to Production
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
