name: Deploy Codex PR to Vercel Production

on:
  push:
    branches:
      - shwdtf-* # Codex PRs
      - codex/*  # Additional Codex-style branches

jobs:
  deploy-to-vercel:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Production Deploy
        run: |
          curl -X POST "https://api.vercel.com/v1/integrations/deploy/prj_fZtOwXp0ToGe87kfUosIkQgXMEQY" \
          -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{"target":"production"}'
