name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to Firebase Hosting
        run: npx firebase deploy --only hosting

      - name: Build and Deploy to Cloud Run
        run: |
          gcloud builds submit --quiet
          gcloud run deploy next-app \
            --image gcr.io/aote-pms/aote-pms:latest \
            --region=us-central1 \
            --platform managed \
            --allow-unauthenticated \
            --quiet
