# .github/workflows/e2e-on-deploy.yml
name: E2E on Vercel Deployments

on:
  deployment_status:

jobs:
  # Full tests on Preview
  cypress_preview:
    if: >
      github.event.deployment_status.state == 'success' &&
      github.event.deployment_status.deployment.environment == 'Preview' &&
      github.event.deployment_status.environment_url != ''
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 1 }
      - name: Set base URL
        id: base
        run: echo "url=${{ github.event.deployment_status.environment_url }}" >> "$GITHUB_OUTPUT"
      - name: Cypress (Preview – full suite)
        uses: cypress-io/github-action@v6
        with:
          install-command: npm ci --omit=optional
          browser: chrome
          headless: true
          config: baseUrl=${{ steps.base.outputs.url }}
          spec: |
            cypress/e2e/add_payment_cascade.cy.tsx
            cypress/e2e/dialog_overlay.cy.js
        env:
          CYPRESS_BASE_URL: ${{ steps.base.outputs.url }}
      - name: Upload Cypress videos
        uses: actions/upload-artifact@v4
        with: { name: cypress-videos-preview, path: cypress/videos, if-no-files-found: ignore }
      - name: Upload Cypress screenshots
        uses: actions/upload-artifact@v4
        with: { name: cypress-screenshots-preview, path: cypress/screenshots, if-no-files-found: ignore }
      - name: Summary
        run: |
          {
            echo "## E2E (Preview) ✅"
            echo ""
            echo "- URL: ${{ steps.base.outputs.url }}"
            echo "- Specs: add_payment_cascade, dialog_overlay"
          } >> "$GITHUB_STEP_SUMMARY"

  # Safe smoke tests on Production
  cypress_production:
    if: >
      github.event.deployment_status.state == 'success' &&
      github.event.deployment_status.deployment.environment == 'Production' &&
      github.event.deployment_status.environment_url != ''
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 1 }
      - name: Set base URL
        id: base
        run: echo "url=${{ github.event.deployment_status.environment_url }}" >> "$GITHUB_OUTPUT"
      - name: Cypress (Production – smoke only)
        uses: cypress-io/github-action@v6
        with:
          install-command: npm ci --omit=optional
          browser: chrome
          headless: true
          config: baseUrl=${{ steps.base.outputs.url }}
          # Make this spec non-mutating (no writes!)
          spec: cypress/e2e/smoke.cy.ts
        env:
          CYPRESS_BASE_URL: ${{ steps.base.outputs.url }}
      - name: Upload Cypress videos
        uses: actions/upload-artifact@v4
        with: { name: cypress-videos-prod, path: cypress/videos, if-no-files-found: ignore }
      - name: Upload Cypress screenshots
        uses: actions/upload-artifact@v4
        with: { name: cypress-screenshots-prod, path: cypress/screenshots, if-no-files-found: ignore }
      - name: Summary
        run: |
          {
            echo "## E2E (Production) ✅"
            echo ""
            echo "- URL: ${{ steps.base.outputs.url }}"
            echo "- Specs: smoke"
          } >> "$GITHUB_STEP_SUMMARY"
