name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out your code
      - uses: actions/checkout@v4

      # 2) (Optional but recommended) Set Node.js version
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3) Install all dependencies
      - name: Install dependencies
        run: npm ci

      # 4) Build your project
      - name: Build
        run: npm run build

      # 5) Deploy to Firebase Hosting
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_AOTE_PMS }}
          channelId: live
          projectId: aote-pms
