name: PR Diff — Manual Refresh

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: PR number to refresh
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch PR metadata
        id: meta
        uses: actions/github-script@v7
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: Number('${{ github.event.inputs.pr_number }}')
            });
            core.setOutput('base_sha', pr.data.base.sha);
            core.setOutput('head_sha', pr.data.head.sha);
            core.setOutput('branch', pr.data.head.ref);

      - name: Checkout PR HEAD
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ steps.meta.outputs.head_sha }}

      - name: Generate diff bundle
        env:
          BASE_SHA: ${{ steps.meta.outputs.base_sha }}
          HEAD_SHA: ${{ steps.meta.outputs.head_sha }}
          PR_NUMBER: ${{ github.event.inputs.pr_number }}
        run: |
          mkdir -p docs/context
          git diff --name-status "$BASE_SHA" "$HEAD_SHA" > /tmp/changed.txt || true
          git diff --stat "$BASE_SHA" "$HEAD_SHA" > /tmp/stat.txt || true
          git diff "$BASE_SHA" "$HEAD_SHA" | head -n 4000 > /tmp/diff.patch || true
          {
            echo "# PR #$PR_NUMBER — Diff Summary"
            echo
            echo "## Changed Files"
            echo
            echo '```txt'; cat /tmp/changed.txt; echo '```'
            echo
            echo "## Stats"
            echo
            echo '```txt'; cat /tmp/stat.txt; echo '```'
            echo
            echo "## Unified Diff (truncated)"
            echo
            echo '```diff'; cat /tmp/diff.patch; echo '```'
          } > "docs/context/PR-${PR_NUMBER}.md"
          cp "docs/context/PR-${PR_NUMBER}.md" context-bundle.md

      - name: Commit diff file back to PR branch
        env:
          PR_BRANCH: ${{ steps.meta.outputs.branch }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/context/PR-*.md context-bundle.md || true
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "docs: manual refresh for #${{ github.event.inputs.pr_number }}"
            git push origin "HEAD:${PR_BRANCH}"
          fi

      - name: Comment links
        uses: actions/github-script@v7
        env:
          SNAPSHOT: ${{ github.sha }}
        with:
          script: |
            const { context, github } = require('@actions/github');
            const num = Number('${{ github.event.inputs.pr_number }}');
            const repo = context.repo.owner + '/' + context.repo.repo;
            const path = `docs/context/PR-${num}.md`;
            const snapshot = `https://raw.githubusercontent.com/${repo}/${process.env.SNAPSHOT}/${path}`;
            const evergreen = `https://github.com/${repo}/blob/${{ steps.meta.outputs.branch }}/${path}`;
            const marker = '<!-- pr-diff-file-sticky -->';
            const body = ['**Diff file refreshed.**', `- Evergreen: ${evergreen}`, `- Snapshot: ${snapshot}`, '', `_File path:_ ${path}`, marker].join('\n');
            const { data: comments } = await github.rest.issues.listComments({ owner: context.repo.owner, repo: context.repo.repo, issue_number: num });
            const existing = comments.find(c => c.user?.type === 'Bot' && c.body?.includes(marker));
            if (existing) await github.rest.issues.updateComment({ owner: context.repo.owner, repo: context.repo.repo, comment_id: existing.id, body });
            else await github.rest.issues.createComment({ owner: context.repo.owner, repo: context.repo.repo, issue_number: num, body });
