name: PR Diff Archive on Merge

on:
  pull_request:
    types: [closed]

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: pr-diff-archive-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  archive:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout base branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.base.ref }}

      - name: Fetch PR diff and metadata
        id: grab
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p docs/context/merged
          # Get machine-readable metadata
          curl -sSL -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${GH_TOKEN}" \
            "https://api.github.com/repos/${REPO}/pulls/${PR_NUMBER}" > /tmp/meta.json

          MERGE_SHA=$(jq -r '.merge_commit_sha' /tmp/meta.json)
          BASE_REF=$(jq -r '.base.ref'           /tmp/meta.json)
          HEAD_REF=$(jq -r '.head.ref'           /tmp/meta.json)
          TITLE=$(jq -r '.title'                 /tmp/meta.json)
          USER=$(jq -r '.user.login'             /tmp/meta.json)

          # Get unified diff as text
          curl -sSL -H "Accept: application/vnd.github.v3.diff" \
            -H "Authorization: Bearer ${GH_TOKEN}" \
            "https://api.github.com/repos/${REPO}/pulls/${PR_NUMBER}" > /tmp/pr.diff

          OUT="docs/context/merged/PR-${PR_NUMBER}-${MERGE_SHA}.md"
          {
            echo "# PR #${PR_NUMBER} — Merged Diff"
            echo
            echo "- **Title**: ${TITLE}"
            echo "- **Author**: @${USER}"
            echo "- **Base branch at merge**: \`${BASE_REF}\`"
            echo "- **Merge commit**: \`${MERGE_SHA}\`"
            echo
            echo "## Unified Diff"
            echo
            echo '```diff'
            cat /tmp/pr.diff
            echo '```'
          } > "$OUT"

          echo "out=$OUT" >> $GITHUB_OUTPUT

      - name: Commit archive file
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add ${{ steps.grab.outputs.out }}
          git commit -m "docs(archive): PR #${{ github.event.pull_request.number }} merged diff"
          git push

      - name: Comment link on PR
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const path = "${{ steps.grab.outputs.out }}";
            const url = `https://github.com/${context.repo.owner}/${context.repo.repo}/blob/${pr.base.ref}/${path}`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              body: `Final diff snapshot archived: ${url}`
            });
