name: PR Diff File

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  generate-and-commit:
    if: ${{ github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest
    concurrency:
      group: pr-diff-file-${{ github.event.pull_request.number }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Compute refs
        id: refs
        run: |
          echo "NUM=${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
          echo "BASE=${{ github.event.pull_request.base.sha }}" >> $GITHUB_OUTPUT
          echo "HEAD=${{ github.event.pull_request.head.sha }}" >> $GITHUB_OUTPUT
          echo "HEAD_REF=${{ github.event.pull_request.head.ref }}" >> $GITHUB_OUTPUT
          echo "HEAD_REPO=${{ github.event.pull_request.head.repo.full_name }}" >> $GITHUB_OUTPUT
          echo "THIS_REPO=${{ github.repository }}" >> $GITHUB_OUTPUT

      - name: Generate bundle file
        run: |
          mkdir -p docs/context
          NUM="${{ steps.refs.outputs.NUM }}"
          BASE="${{ steps.refs.outputs.BASE }}"
          HEAD="${{ steps.refs.outputs.HEAD }}"
          OUT="docs/context/PR-${NUM}.md"
          {
            echo "# PR #$NUM – Diff Bundle"
            echo
            echo "_Base:_ \`${BASE::7}\`  _Head:_ \`${HEAD::7}\`"
            echo "_Generated:_ $(date -u '+%Y-%m-%d %H:%M UTC')"
            echo
            echo "## Changed Files"
            echo
            git diff --name-status "$BASE...$HEAD" | sed 's/^/- /'
            echo
            echo "## Compact Diff Hunks"
            echo
            echo '```diff'
            git diff --unified=0 "$BASE...$HEAD" | head -n 4000
            echo '```'
          } > "$OUT"

      - name: Commit file to PR branch (same-repo only)
        if: ${{ steps.refs.outputs.HEAD_REPO == steps.refs.outputs.THIS_REPO }}
        env:
          REF: ${{ steps.refs.outputs.HEAD_REF }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/context/PR-*.md
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "chore(context): update PR diff bundle"
          git push origin "HEAD:$REF"

      - name: Upload artifact (fallback for forks)
        if: ${{ steps.refs.outputs.HEAD_REPO != steps.refs.outputs.THIS_REPO }}
        uses: actions/upload-artifact@v4
        with:
          name: pr-${{ steps.refs.outputs.NUM }}-bundle
          path: docs/context/PR-${{ steps.refs.outputs.NUM }}.md
          if-no-files-found: error
